### ISSUE TITLE
Output space delimited issue

### ISSUE THREAD

**Issue by sheenamt** [rbundschuh/MonoSeq#1]
Is it possible to update how the output is printed? 

line 270 of monoseq.c is currently:

 printf("%4d %3d %3d ",coverage,maxlen,pDescription->RepeatLength);

Is there a reason isn't simply space delimited? 

printf("%1d %1d %1d ",coverage,maxlen,pDescription->RepeatLength);

**Comment by rbundschuh** [comment]
To whom it may concern,

Thanks for the suggestion.  While I like the more human readable output 
myself, I now added a "-d <del>" option that chooses the output 
delimiter and removes the extra spaces.  Thus, with "-d ' '" you should 
get the single space delimited format you were looking for.

   Yours
         Ralf

**Comment by sheenamt** [comment]
Thanks!
